# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysqlclaim
# spec:
#   accessModes:
#     - ReadWriteOnce
#   volumeMode: Filesystem
#   resources:
#     requests:
#       storage: 5Gi
  #storageClassName: "standard-rwo"

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysqlclaim
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
# storageClassName: "standarddisk"

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlclaim0
spec:
  storageClassName: "standard-rwo"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysqlclaim1
spec:
  storageClassName: "standard-rwo"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: mysqlclaim0
  gcePersistentDisk:
    pdName: mysqlclaim2
    fsType: ext4