apiVersion: v1
kind: Pod
metadata:
  name: nginx-proxy
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: PROXY_STATUS
          valueFrom:
            configMapKeyRef:
              name: proxy-config
              key: proxy_status