apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
data:
  proxy_status: enabled
---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-proxy
spec:
  containers:
    - name: test-container
      image: nginx
      env:
        - name: PROXY_STATUS
          valueFrom:
            configMapKeyRef:
              name: proxy-config
              key: proxy_status
